#!/bin/bash
set -eo pipefail

# shellcheck source=/dev/null
source ./library.sh

apt-get update && \
    apt-get install -y -qq \
    zsh \
    git \
    wget \
    curl \
    unzip \
    fonts-powerline \
    && rm -rf /var/lib/apt/lists/*

echo_blue "Installing Oh My Zsh..."
# RUNZSH=no CHSH=yes sh -c "$(curl -fsSL https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh)" "" --unattended
if [ ! -d "${HOME}/.oh-my-zsh" ]; then
    RUNZSH=no CHSH=yes sh -c "$(curl -fsSL https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh)" "" --unattended
else
    echo "Oh My Zsh is already installed in ${HOME}/.oh-my-zsh"
fi

if [[ -n "${THEME}" ]]; then
    echo_blue "Installing theme: ${THEME}"
    if [[ "${THEME}" == "powerlevel10k/powerlevel10k" ]]; then
        if [ ! -d "${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k" ]; then
            git clone --depth=1 https://github.com/romkatv/powerlevel10k.git "${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k"
        else
            echo "theme ${THEME} already installed."
        fi
    fi
fi

if [[ -n "${PLUGINS}" ]]; then
    echo_blue "Installing plugins: ${PLUGINS}"
    IFS=',' read -ra plugins <<< "${PLUGINS}"
    for plugin in "${plugins[@]}"; do
        git clone "https://github.com/${plugin}" "${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/plugins/$(basename "${plugin}")"
    done
fi

if [[ "${INSTALLFONTS}" == "true" ]]; then
    echo_blue "Installing FiraCode Nerd Font..."
    FONTS_DIR="${HOME}/.local/share/fonts"
    mkdir -p "${FONTS_DIR}"
    curl -fsSL -o /tmp/FiraCode.zip \
        https://github.com/ryanoasis/nerd-fonts/releases/download/v3.0.0/FiraCode.zip
    unzip -q -o /tmp/FiraCode.zip -d "${FONTS_DIR}"
    rm -f /tmp/FiraCode.zip
    fc-cache -f
fi

echo_green "Configuring zsh shell..."
cat << EOF > "${HOME}/.zshrc"
# Generated by Oh My Zsh feature
export ZSH="\$HOME/.oh-my-zsh"
ZSH_THEME="${THEME}"
plugins=(${PLUGINS//,/ })

source "\$ZSH/oh-my-zsh.sh"
EOF

# Copy custom zsh configuration files
echo_blue "Copying custom .zshrc and .p10k.zsh..."
cp .zshrc "${HOME}/.zshrc"
cp .p10k.zsh "${HOME}/.p10k.zsh"

if [[ -f "${HOME}/.purepower" ]]; then
    echo "source ~/.purepower" >> "${HOME}/.zshrc"
fi
